version: 2.1


dependencies:
  override:
    - bash ./build_tools/circle/install.sh:

jobs:
  test:
    machine:
      python:
        version: 3.5.1
    steps:
      - bash ./build_tools/circle/build.sh

  deployment:
    machine:
      python:
        version: 3.5.1
    push:
      branch: master
    steps:
       - bash ./build_tools/circle/deploy.sh

  general:
    # Open the doc to the API
    artifacts:
      - ~/site

workflows:
  test_and_deploy:
    jobs:
      - test
      - deployment
      - general
