version: 2.1

machine:
  python:
    version: 3.5.1

dependencies:
  override:
    - bash ./build_tools/circle/install.sh:

jobs:
  test:
    commands:
      - bash ./build_tools/circle/build.sh

  deployment:
   push:
     branch: master
     commands:
       - bash ./build_tools/circle/deploy.sh

  general:
    # Open the doc to the API
    artifacts:
      - ~/site

workflows:
  test_and_deploy:
    jobs:
      - test
      - deployment
      - general
