version: 2.1


dependencies:
  override:
    - bash build_tools/circle/install.sh:

jobs:
  build_and_test:
    machine: True
    steps:
      - run build_tools/circle/build.sh

  deployment:
    machine: True
    steps:
      - run build_tools/circle/deploy.sh

  general:
    # Open the doc to the API
    machine: True
    steps:
      - store_artifacts:
        path: /bin/final_build

workflows:
  build_and_deploy:
    jobs:
      - build_and_test
      - deployment:
          filters:
            branches:
              only: master 
      - general
